name: "CI: External Usage"
on:
  pull_request:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash # Set the default shell to bash.

jobs:
  validate-external-usage:
    runs-on: ubuntu-latest
    # Validate that the action itself can be run without having checked out the repository.
    steps:
      - name: Run the 'expose-tunnel' action from main
        uses: codetalkio/expose-tunnel@main
        id: expose-tunnel
        with:
          service: bore.pub
          port: 80
