name: "CI: Tunnel Forwarding"
on:
  pull_request:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash # Set the default shell to bash.

jobs:
  tunnel:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      # Check out https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#expanding-or-adding-matrix-configurations
      # for details on matrix strategies.
      matrix:
        include:
          # Test managed localhost.run.
          - service: localhost.run
            port: 8080
          # Test managed bore.
          - service: bore.pub
            port: 8080
          # Test self-hosted bore.
          - service: bore.selfhosted
            selfHostedEndpoint: "localhost"
            port: 8080
          # Test self-hosted bore with a secret.
          - service: bore.selfhosted
            secret: secret-value
            selfHostedEndpoint: "localhost"
            port: 8080
          # Trigger fallback mode.
          - service: bore.selfhosted
            fallback: '["bore.pub"]'
            selfHostedEndpoint: "localhost"
            port: 8080

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Starting a simple node.js http-server in the background
        run: |
          npm install -g http-server
          http-server &

      - name: Wait until local server is ready
        run: timeout 1m bash -c "while ! curl -sSf http://127.0.0.1:8080; do sleep 1 ; done"

      # See https://github.com/ekzhang/bore for how to setup and configure bore.
      - name: Set up bore locally
        if: matrix.service == 'bore.selfhosted' && matrix.selfHostedEndpoint && !matrix.fallback
        run: |
          wget https://github.com/ekzhang/bore/releases/download/v0.4.0/bore-v0.4.0-x86_64-unknown-linux-musl.tar.gz
          tar -xf bore-v0.4.0-x86_64-unknown-linux-musl.tar.gz
          [[ "${{ matrix.secret }}" != "" ]] && (./bore server --secret ${{ matrix.secret }} &) || (./bore server &)
          sleep 2

      - name: Run the 'expose-tunnel' action from the local source
        uses: ./
        id: expose-tunnel
        with:
          service: ${{ matrix.service }}
          port: ${{ matrix.port }}
          selfHostedEndpoint: ${{ matrix.selfHostedEndpoint }}
          fallback: ${{ matrix.fallback }}
          secret: ${{ matrix.secret }}

      - name: Check the tunnel url was set
        env:
          TUNNEL_URL: ${{ steps.expose-tunnel.outputs.tunnel-url }}
        run: |
          echo "Tunnel URL was set to: '${{ steps.expose-tunnel.outputs.tunnel-url }}'"
          [[ "${{ steps.expose-tunnel.outputs.tunnel-url }}" != "" ]] && echo "URL passed checks." || exit 1

      - name: Check tunnel is accessible
        run: curl -sSf ${{ steps.expose-tunnel.outputs.tunnel-url }}
